"""add test builder tables

Revision ID: 020e2f439aba
Revises: d7edcce8df80
Create Date: 2026-07-30 13:21:46.552717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020e2f439aba'
down_revision = 'd7edcce8df80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qid', sa.String(length=40), nullable=False),
    sa.Column('subtopic_code', sa.String(length=20), nullable=False),
    sa.Column('unit_code', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=1), nullable=False),
    sa.Column('subtopic_title', sa.Text(), nullable=False),
    sa.Column('is_hl_only', sa.Boolean(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('command_term', sa.String(length=60), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct_options', sa.Text(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('marking_guidance', sa.Text(), nullable=True),
    sa.Column('common_mistakes', sa.Text(), nullable=True),
    sa.Column('ai_checklist', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qid')
    )
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.create_index('ix_test_question_subtopic', ['subtopic_code'], unique=False)
        batch_op.create_index('ix_test_question_unit', ['unit_code'], unique=False)

    op.create_table('test_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_paper_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_paper_id'], ['test_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_assignments_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_assignments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_assignments_test_paper_id'), ['test_paper_id'], unique=False)

    op.create_table('test_paper_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_paper_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ),
    sa.ForeignKeyConstraint(['test_paper_id'], ['test_papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_paper_id', 'question_id', name='uq_test_paper_question')
    )
    with op.batch_alter_table('test_paper_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_paper_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_paper_questions_test_paper_id'), ['test_paper_id'], unique=False)

    op.create_table('test_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_paper_id', sa.Integer(), nullable=False),
    sa.Column('test_assignment_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_marks_awarded', sa.Integer(), nullable=True),
    sa.Column('total_marks_possible', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_assignment_id'], ['test_assignments.id'], ),
    sa.ForeignKeyConstraint(['test_paper_id'], ['test_papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_paper_id', 'student_id', name='uq_test_submission_single_attempt')
    )
    with op.batch_alter_table('test_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_submissions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_submissions_test_assignment_id'), ['test_assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_submissions_test_paper_id'), ['test_paper_id'], unique=False)

    op.create_table('test_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('selected_options', sa.Text(), nullable=True),
    sa.Column('auto_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_awarded', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['test_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_test_answer_question')
    )
    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_answers_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_answers_submission_id'))
        batch_op.drop_index(batch_op.f('ix_test_answers_question_id'))

    op.drop_table('test_answers')
    with op.batch_alter_table('test_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_submissions_test_paper_id'))
        batch_op.drop_index(batch_op.f('ix_test_submissions_test_assignment_id'))
        batch_op.drop_index(batch_op.f('ix_test_submissions_student_id'))

    op.drop_table('test_submissions')
    with op.batch_alter_table('test_paper_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_paper_questions_test_paper_id'))
        batch_op.drop_index(batch_op.f('ix_test_paper_questions_question_id'))

    op.drop_table('test_paper_questions')
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_assignments_test_paper_id'))
        batch_op.drop_index(batch_op.f('ix_test_assignments_student_id'))
        batch_op.drop_index(batch_op.f('ix_test_assignments_class_id'))

    op.drop_table('test_assignments')
    op.drop_table('test_papers')
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_test_question_unit')
        batch_op.drop_index('ix_test_question_subtopic')

    op.drop_table('test_questions')
    # ### end Alembic commands ###
