"""initial schema: users, classes, enrollments, assignments, activity

Revision ID: 067a3eb69e1a
Revises: 
Create Date: 2026-07-11 20:43:38.738089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067a3eb69e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('book_folder', sa.String(length=120), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'book_folder', 'page_id', name='uq_student_page')
    )
    with op.batch_alter_table('reading_activity', schema=None) as batch_op:
        batch_op.create_index('ix_activity_student_book', ['student_id', 'book_folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_activity_student_id'), ['student_id'], unique=False)

    op.create_table('class_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_class_student')
    )
    op.create_table('reading_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('book_folder', sa.String(length=120), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_assignments_class_id'), ['class_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_assignments_class_id'))

    op.drop_table('reading_assignments')
    op.drop_table('class_enrollments')
    with op.batch_alter_table('reading_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_activity_student_id'))
        batch_op.drop_index('ix_activity_student_book')

    op.drop_table('reading_activity')
    op.drop_table('classes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
