"""Add description field to BugHuntSnippet

Revision ID: 07636ae09ec7
Revises: 0a9986f7d4a7
Create Date: 2026-08-04 11:28:47.519777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07636ae09ec7'
down_revision = '0a9986f7d4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug_hunt_snippets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug_hunt_snippets', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
