"""add class games tables

Revision ID: 0a9986f7d4a7
Revises: n0o1p2q3r4s5
Create Date: 2026-08-03 12:01:20.527027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9986f7d4a7'
down_revision = 'n0o1p2q3r4s5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_hunt_snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('bugs', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('topic_label', sa.String(length=120), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=30), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_sessions_class_id'), ['class_id'], unique=False)

    op.create_table('game_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_game_participant')
    )
    with op.batch_alter_table('game_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_participants_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_participants_student_id'), ['student_id'], unique=False)

    op.create_table('game_round_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['game_participants.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'participant_id', 'round_index', 'attempt', name='uq_game_round_answer')
    )
    with op.batch_alter_table('game_round_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_round_answers_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_round_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_round_answers_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slide_decks_topic_id'))
        batch_op.create_index(batch_op.f('ix_resources_topic_id'), ['topic_id'], unique=False)

    with op.batch_alter_table('student_report_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_report_cache_student_id'))
        batch_op.create_index(batch_op.f('ix_student_report_cache_student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_report_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_report_cache_student_id'))
        batch_op.create_index(batch_op.f('ix_student_report_cache_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_topic_id'))
        batch_op.create_index(batch_op.f('ix_slide_decks_topic_id'), ['topic_id'], unique=False)

    with op.batch_alter_table('game_round_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_round_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_game_round_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_game_round_answers_participant_id'))

    op.drop_table('game_round_answers')
    with op.batch_alter_table('game_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_participants_student_id'))
        batch_op.drop_index(batch_op.f('ix_game_participants_session_id'))

    op.drop_table('game_participants')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_sessions_class_id'))

    op.drop_table('game_sessions')
    op.drop_table('bug_hunt_snippets')
    # ### end Alembic commands ###
