"""drop opens_at and due_date from test_assignments

Revision ID: 1d61b2973812
Revises: 9ab4fa5897d8
Create Date: 2026-07-30 15:34:54.985065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d61b2973812'
down_revision = '9ab4fa5897d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('opens_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opens_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
