"""add reading_daily_log

Revision ID: 2c05e2e85a1e
Revises: 57ffe3c1b05b
Create Date: 2026-07-15 20:26:03.220433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c05e2e85a1e'
down_revision = '57ffe3c1b05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_daily_log_student_date')
    )
    with op.batch_alter_table('reading_daily_log', schema=None) as batch_op:
        batch_op.create_index('ix_daily_log_student_date', ['student_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_daily_log_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('heading_styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heading_styles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heading_styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heading_styles_user_id'))

    with op.batch_alter_table('reading_daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_daily_log_student_id'))
        batch_op.drop_index('ix_daily_log_student_date')

    op.drop_table('reading_daily_log')
    # ### end Alembic commands ###
