"""Update folder models for book-specific organization

Revision ID: 43c41537a360
Revises: 54544bdd963b
Create Date: 2026-07-12 20:40:00.060093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c41537a360'
down_revision = '54544bdd963b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_page_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_folder', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['book_page_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_page_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_page_folders_book_folder'), ['book_folder'], unique=False)
        batch_op.create_index('ix_folder_book', ['book_folder'], unique=False)

    op.create_table('book_page_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_folder', sa.String(length=120), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['book_page_folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_folder', 'page_id', name='uq_book_page_assignment')
    )
    with op.batch_alter_table('book_page_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_book_page', ['book_folder', 'page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_page_assignments_book_folder'), ['book_folder'], unique=False)

    op.drop_table('resource_assignments')
    op.drop_table('resource_folders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_folders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['resource_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('folder_id', sa.INTEGER(), nullable=True),
    sa.Column('assigned_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['resource_folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', name=op.f('uq_resource_assignment'))
    )
    with op.batch_alter_table('book_page_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_page_assignments_book_folder'))
        batch_op.drop_index('ix_assignment_book_page')

    op.drop_table('book_page_assignments')
    with op.batch_alter_table('book_page_folders', schema=None) as batch_op:
        batch_op.drop_index('ix_folder_book')
        batch_op.drop_index(batch_op.f('ix_book_page_folders_book_folder'))

    op.drop_table('book_page_folders')
    # ### end Alembic commands ###
