"""Add resource folder management

Revision ID: 54544bdd963b
Revises: c8d9e0f1a2b3
Create Date: 2026-07-12 20:32:34.651811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54544bdd963b'
down_revision = 'c8d9e0f1a2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['resource_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['resource_folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', name='uq_resource_assignment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_assignments')
    op.drop_table('resource_folders')
    # ### end Alembic commands ###
