"""add icon fields to test_questions

Revision ID: 5836c1a870b7
Revises: c4f882d173c2
Create Date: 2026-07-30 17:16:43.750280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5836c1a870b7'
down_revision = 'c4f882d173c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_library', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('icon_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('icon_source_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('visual_search_terms', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_column('visual_search_terms')
        batch_op.drop_column('icon_source_url')
        batch_op.drop_column('icon_name')
        batch_op.drop_column('icon_library')

    # ### end Alembic commands ###
