"""add unit plan tables

Revision ID: 5c6b70c5cfc6
Revises: j6k7l8m9n0o1
Create Date: 2026-07-27 22:07:29.419086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6b70c5cfc6'
down_revision = 'j6k7l8m9n0o1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_plan_semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('date_range', sa.String(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('unit_plan_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('part', sa.String(length=10), nullable=False),
    sa.Column('part_label', sa.String(length=120), nullable=True),
    sa.Column('hl_only', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_position', sa.Integer(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_table('unit_plan_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('content_focus', sa.String(length=400), nullable=True),
    sa.Column('big_idea', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('is_exam', sa.Boolean(), nullable=False),
    sa.Column('calendar_dates', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('merged_note', sa.Text(), nullable=True),
    sa.Column('hl', sa.String(length=300), nullable=True),
    sa.Column('sl', sa.String(length=300), nullable=True),
    sa.Column('syllabus', sa.String(length=120), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['unit_plan_semesters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'week_number', name='uq_unit_plan_week')
    )
    with op.batch_alter_table('unit_plan_weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_plan_weeks_semester_id'), ['semester_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_plan_weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_plan_weeks_semester_id'))

    op.drop_table('unit_plan_weeks')
    op.drop_table('unit_plan_topics')
    op.drop_table('unit_plan_semesters')
    # ### end Alembic commands ###
