"""add if_wrong_explainer to test_questions

Revision ID: 85496456a61f
Revises: 5836c1a870b7
Create Date: 2026-07-30 18:07:20.936657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85496456a61f'
down_revision = '5836c1a870b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('if_wrong_explainer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_column('if_wrong_explainer')

    # ### end Alembic commands ###
