"""add resource_type to reading_assignments

Revision ID: 8e6e64962471
Revises: 067a3eb69e1a
Create Date: 2026-07-11 21:38:07.618577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6e64962471'
down_revision = '067a3eb69e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(length=20), server_default='book_page', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_assignments', schema=None) as batch_op:
        batch_op.drop_column('resource_type')

    # ### end Alembic commands ###
