"""add access_code to test_assignments

Revision ID: 9ab4fa5897d8
Revises: 020e2f439aba
Create Date: 2026-07-30 13:49:21.964648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab4fa5897d8'
down_revision = '020e2f439aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_code', sa.String(length=8), nullable=False))
        batch_op.create_unique_constraint('uq_test_assignment_access_code', ['access_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_test_assignment_access_code', type_='unique')
        batch_op.drop_column('access_code')

    # ### end Alembic commands ###
