"""add student confidence tracking

Revision ID: 9b9f4cfb2f4e
Revises: 8e6e64962471
Create Date: 2026-07-12 04:04:37.658914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9f4cfb2f4e'
down_revision = '8e6e64962471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_confidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('book_folder', sa.String(length=120), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=False),
    sa.Column('confidence_level', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'book_folder', 'page_id', name='uq_student_confidence_page')
    )
    with op.batch_alter_table('student_confidence', schema=None) as batch_op:
        batch_op.create_index('ix_confidence_student_book', ['student_id', 'book_folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_confidence_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_confidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_confidence_student_id'))
        batch_op.drop_index('ix_confidence_student_book')

    op.drop_table('student_confidence')
    # ### end Alembic commands ###
