"""add correct_streak to flashcard_progress

Revision ID: b8bf8d2e0be7
Revises: 2c05e2e85a1e
Create Date: 2026-07-15 20:56:52.301957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bf8d2e0be7'
down_revision = '2c05e2e85a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_streak', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_progress', schema=None) as batch_op:
        batch_op.drop_column('correct_streak')

    # ### end Alembic commands ###
