"""add level_filter to test_assignments

Revision ID: c4f882d173c2
Revises: dd31564a0c7e
Create Date: 2026-07-30 16:50:50.108856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f882d173c2'
down_revision = 'dd31564a0c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_filter', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.drop_column('level_filter')

    # ### end Alembic commands ###
