"""add taught flag to unit plan weeks

Revision ID: d7edcce8df80
Revises: 5c6b70c5cfc6
Create Date: 2026-07-28 01:10:48.968438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7edcce8df80'
down_revision = '5c6b70c5cfc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_plan_weeks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taught', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_plan_weeks', schema=None) as batch_op:
        batch_op.drop_column('taught')

    # ### end Alembic commands ###
