"""make test assignment access_code nullable

Revision ID: dd31564a0c7e
Revises: 1d61b2973812
Create Date: 2026-07-30 16:25:05.650259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd31564a0c7e'
down_revision = '1d61b2973812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.alter_column('access_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_assignments', schema=None) as batch_op:
        batch_op.alter_column('access_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###
