"""add is_simulated flag to test_submissions

Revision ID: e748d217f567
Revises: 85496456a61f
Create Date: 2026-07-30 21:16:59.559509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e748d217f567'
down_revision = '85496456a61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_simulated', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_submissions', schema=None) as batch_op:
        batch_op.drop_column('is_simulated')

    # ### end Alembic commands ###
