"""Add feedback field and StudentFeedbackInsight model

Revision ID: ee0e7217c194
Revises: c1d2e3f4a5b6
Create Date: 2026-07-16 18:15:34.142642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0e7217c194'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_feedback_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('extracted_keywords', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['quiz_answers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_feedback_insights', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_insight_student', ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_feedback_insights_answer_id'), ['answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_feedback_insights_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_feedback_insights_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    with op.batch_alter_table('student_feedback_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_feedback_insights_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_feedback_insights_question_id'))
        batch_op.drop_index(batch_op.f('ix_student_feedback_insights_answer_id'))
        batch_op.drop_index('ix_feedback_insight_student')

    op.drop_table('student_feedback_insights')
    # ### end Alembic commands ###
